image: Ubuntu1804

branches:
  only:
    - main

environment:
  matrix:
    - nodejs_version: "14"

init:
  # Установка NVM и Node.js
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install $nodejs_version
  - nvm use $nodejs_version

install:
  # Установка зависимостей с помощью Yarn
  - echo "Installing dependencies..."
  - yarn install

build_script:
  # Сборка проекта
  - echo "Building the project..."
  - yarn run build

artifacts:
  # Определение артефактов для сохранения собранного проекта
  - path: dist
    name: artifact

deploy_script:
  - echo "Configuring Git..."
  - git config --global credential.helper store
  - git config --global user.name "Roman9456"
  - git config --global user.email "smolyakov_ra@mail.ru"
  - echo "https://${GITHUB_TOKEN}:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - echo "Contents of dist directory:"
  - ls -al dist
  - echo "Checking for changes in the build..."
  # Проверка наличия ветки gh-pages
  - if ! git ls-remote origin gh-pages | grep gh-pages > /dev/null; then git checkout -b gh-pages; fi
  # Очистка содержимого временной папки gh-pages-temp
  - rm -rf gh-pages-temp/*
  # Копирование содержимого папки dist во временную папку gh-pages-temp
  - cp -r dist/. gh-pages-temp/
  - cd gh-pages-temp
  # Добавление всех файлов в гит
  - git add .
  # Коммит изменений
  - git commit -m "Deploy to GitHub Pages"
  # Пуш временной папки на ветку gh-pages
  - git push origin gh-pages-temp:gh-pages
  - echo "Deployment complete."
